"use client";

import { FormEvent, PointerEvent as ReactPointerEvent, useEffect, useRef, useState } from "react";
import NaverMap, { type RouteLeg } from "./NaverMap";

export type Place = { id: string; name: string; category: string; address: string; longitude: number; latitude: number; link?: string };
export type RouteEndpoint = { name: string; longitude: number; latitude: number };
type DayPlan = { id: string; label: string; date: string; start: RouteEndpoint; goal: RouteEndpoint; places: Place[]; candidates?: Record<string,Place[]> };
type TripPlan = { id: string; title: string; days: DayPlan[]; updatedAt: number };
const initialSavedPlaces: Place[] = [];
const initialDays: DayPlan[] = [
  {id:"day-1",label:"1일차",date:"날짜 미정",start:{name:"출발지 미정",longitude:127.5,latitude:36.5},goal:{name:"목적지 미정",longitude:127.5,latitude:36.5},places:[]},
];
const initialTrips: TripPlan[] = [{id:"trip-new",title:"새 여행",days:initialDays,updatedAt:Date.now()}];
const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? "";

function nextDateLabel(value:string){const match=value.match(/^(\d{1,2})월\s*(\d{1,2})일$/);if(!match)return "날짜 미정";const date=new Date(2026,Number(match[1])-1,Number(match[2])+1);return `${date.getMonth()+1}월 ${date.getDate()}일`}

export default function Home() {
  const [tab,setTab]=useState<"plan"|"map"|"trips"|"saved">("plan");
  const [trips,setTrips]=useState<TripPlan[]>(initialTrips);
  const [activeTripId,setActiveTripId]=useState("trip-new");
  const [tripsLoaded,setTripsLoaded]=useState(false);
  const [cloudReady,setCloudReady]=useState(false);
  const [days,setDays]=useState<DayPlan[]>(initialDays);
  const [activeDayId,setActiveDayId]=useState("day-1");
  const [savedPlaces,setSavedPlaces]=useState<Place[]>([]);
  const [savedLoaded,setSavedLoaded]=useState(false);
  const [dragIndex,setDragIndex]=useState<number|null>(null);
  const draggedIndex=useRef<number|null>(null);
  const [query,setQuery]=useState("");
  const [results,setResults]=useState<Place[]>([]);
  const [searching,setSearching]=useState(false);
  const [searchError,setSearchError]=useState("");
  const [source,setSource]=useState<"local"|"geocoding"|"">("");
  const [insertIndex,setInsertIndex]=useState<number|null>(null);
  const [candidateFor,setCandidateFor]=useState<string|null>(null);
  const [endpointTarget,setEndpointTarget]=useState<"start"|"goal"|null>(null);
  const [legs,setLegs]=useState<RouteLeg[]>([]);
  const activeDay=days.find((day)=>day.id===activeDayId)??days[0];
  const activeTrip=trips.find((trip)=>trip.id===activeTripId)??trips[0];
  const places=activeDay?.places??[];

  useEffect(()=>{try{const stored=localStorage.getItem("gildam-saved-places");setSavedPlaces(stored?JSON.parse(stored) as Place[]:initialSavedPlaces)}catch{setSavedPlaces(initialSavedPlaces)}finally{setSavedLoaded(true)}},[]);
  useEffect(()=>{if(savedLoaded)localStorage.setItem("gildam-saved-places",JSON.stringify(savedPlaces))},[savedLoaded,savedPlaces]);
  useEffect(()=>{try{const stored=localStorage.getItem("gildam-trips");const legacy=localStorage.getItem("gildam-trip-days");const parsed=stored?JSON.parse(stored) as TripPlan[]:null;if(parsed?.length){setTrips(parsed);setActiveTripId(parsed[0].id);setDays(parsed[0].days);setActiveDayId(parsed[0].days[0].id)}else if(legacy){const legacyDays=JSON.parse(legacy) as DayPlan[];const migrated=[{...initialTrips[0],days:legacyDays}];setTrips(migrated);setDays(legacyDays)}}catch{}finally{setTripsLoaded(true)}},[]);
  useEffect(()=>{if(tripsLoaded)setTrips((items)=>items.map((trip)=>trip.id===activeTripId?{...trip,days,updatedAt:Date.now()}:trip))},[activeTripId,days,tripsLoaded]);
  useEffect(()=>{if(tripsLoaded)localStorage.setItem("gildam-trips",JSON.stringify(trips))},[trips,tripsLoaded]);
  useEffect(()=>{if(!API_BASE||!tripsLoaded||!savedLoaded)return;let cancelled=false;(async()=>{let deviceId=localStorage.getItem("gildam-device-id");if(!deviceId){deviceId=`device_${crypto.randomUUID().replaceAll("-","")}`;localStorage.setItem("gildam-device-id",deviceId)}try{const response=await fetch(`${API_BASE}/api/state`,{headers:{"x-gildam-device":deviceId}});if(response.ok){const data=await response.json() as {trips?:TripPlan[];savedPlaces?:Place[]};if(!cancelled&&data.trips?.length){setTrips(data.trips);setActiveTripId(data.trips[0].id);setDays(data.trips[0].days);setActiveDayId(data.trips[0].days[0].id)}if(!cancelled&&data.savedPlaces?.length)setSavedPlaces(data.savedPlaces)}}finally{if(!cancelled)setCloudReady(true)}})();return()=>{cancelled=true}},[tripsLoaded,savedLoaded]);
  useEffect(()=>{if(!API_BASE||!cloudReady)return;const timer=setTimeout(()=>{const deviceId=localStorage.getItem("gildam-device-id");if(deviceId)fetch(`${API_BASE}/api/state`,{method:"PUT",headers:{"content-type":"application/json","x-gildam-device":deviceId},body:JSON.stringify({trips,savedPlaces})}).catch(()=>{})},700);return()=>clearTimeout(timer)},[cloudReady,trips,savedPlaces]);

  function setPlaces(update:Place[]|((items:Place[])=>Place[])){setDays((items)=>items.map((day)=>day.id===activeDayId?{...day,places:typeof update==="function"?update(day.places):update}:day))}
  function selectDay(id:string){setActiveDayId(id);setLegs([]);setInsertIndex(null);setCandidateFor(null);setEndpointTarget(null);setResults([]);setSearchError("")}
  function addDay(){if(days.length>=5)return;const previous=days[days.length-1];if(previous.goal.name==="목적지 미정"){window.alert(`${previous.label} 목적지를 먼저 설정해 주세요.`);setActiveDayId(previous.id);return}const id=`day-${Date.now()}`;const next:DayPlan={id,label:`${days.length+1}일차`,date:nextDateLabel(previous.date),start:previous.goal,goal:{name:"목적지 미정",longitude:previous.goal.longitude,latitude:previous.goal.latitude},places:[]};setDays((items)=>[...items,next]);setActiveDayId(id);setLegs([])}
  function removeDay(id:string){if(days.length<=1)return;const target=days.find((day)=>day.id===id);if(!target||!window.confirm(`${target.label}(${target.date}) 일정과 장소를 모두 삭제할까요?`))return;const index=days.findIndex((day)=>day.id===id);const remaining=days.filter((day)=>day.id!==id).map((day,i)=>({...day,label:`${i+1}일차`}));setDays(remaining);if(id===activeDayId)setActiveDayId(remaining[Math.max(0,index-1)]?.id??remaining[0].id);setLegs([])}
  function openTrip(id:string){const trip=trips.find((item)=>item.id===id);if(!trip)return;setActiveTripId(id);setDays(trip.days);setActiveDayId(trip.days[0].id);setLegs([]);setTab("plan")}
  function addTrip(){const id=`trip-${Date.now()}`;const first:DayPlan={id:`day-${Date.now()}`,label:"1일차",date:"날짜 미정",start:{name:"출발지 미정",longitude:127.5,latitude:36.5},goal:{name:"목적지 미정",longitude:127.5,latitude:36.5},places:[]};const trip:TripPlan={id,title:`새 여행 ${trips.length+1}`,days:[first],updatedAt:Date.now()};setTrips((items)=>[trip,...items]);setActiveTripId(id);setDays(trip.days);setActiveDayId(first.id);setLegs([]);setTab("plan")}
  function renameTrip(id:string){const trip=trips.find((item)=>item.id===id);if(!trip)return;const title=window.prompt("여행 이름을 입력하세요.",trip.title)?.trim();if(title)setTrips((items)=>items.map((item)=>item.id===id?{...item,title,updatedAt:Date.now()}:item))}
  function removeTrip(id:string){if(trips.length<=1)return;const trip=trips.find((item)=>item.id===id);if(!trip||!window.confirm(`‘${trip.title}’ 여행을 삭제할까요?`))return;const remaining=trips.filter((item)=>item.id!==id);setTrips(remaining);if(id===activeTripId){const next=remaining[0];setActiveTripId(next.id);setDays(next.days);setActiveDayId(next.days[0].id);setLegs([])}}

  async function search(event:FormEvent){event.preventDefault();if(query.trim().length<2)return;setSearching(true);setSearchError("");try{const response=await fetch(`${API_BASE}/api/places/search?q=${encodeURIComponent(query.trim())}`);const data=await response.json() as {places?:Place[];error?:string;source?:"local"|"geocoding"};if(!response.ok)throw new Error(data.error);setResults(data.places??[]);setSource(data.source??"");if(!(data.places??[]).length)setSearchError("검색 결과가 없습니다.");}catch(error){setSearchError(error instanceof Error?error.message:"검색에 실패했습니다.");}finally{setSearching(false)}}
  function addPlace(place:Place){if(places.length>=5){setSearchError("Directions 5에서는 경유지를 최대 5곳까지 추가할 수 있어요.");return}if(places.some((item)=>item.id===place.id))return;setPlaces((items)=>{const next=[...items];next.splice(insertIndex??items.length,0,place);return next});setResults([]);setQuery("");if(insertIndex!==null){setInsertIndex(null);setTab("plan")}}
  function chooseInsertion(index:number){setInsertIndex(index);setCandidateFor(null);setEndpointTarget(null);setResults([]);setSearchError("");setQuery("");setTab("map")}
  function chooseCandidate(id:string){setCandidateFor(id);setInsertIndex(null);setEndpointTarget(null);setResults([]);setSearchError("");setQuery("");setTab("map")}
  function chooseEndpoint(target:"start"|"goal"){setEndpointTarget(target);setCandidateFor(null);setInsertIndex(null);setResults([]);setSearchError("");setQuery("");setTab("map")}
  function setEndpoint(place:Place){if(!endpointTarget)return;setDays((items)=>items.map((day)=>day.id===activeDayId?{...day,[endpointTarget]:{name:place.name,longitude:place.longitude,latitude:place.latitude}}:day));setEndpointTarget(null);setResults([]);setQuery("");setLegs([]);setTab("plan")}
  function addCandidate(place:Place){if(!candidateFor)return;setDays((items)=>items.map((day)=>{if(day.id!==activeDayId)return day;const main=day.places.find((item)=>item.id===candidateFor);const existing=day.candidates?.[candidateFor]??[];if(!main||main.id===place.id||existing.some((item)=>item.id===place.id))return day;return {...day,candidates:{...(day.candidates??{}),[candidateFor]:[...existing,place]}}}));setCandidateFor(null);setResults([]);setQuery("");setTab("plan")}
  function removeCandidate(mainId:string,id:string){setDays((items)=>items.map((day)=>day.id===activeDayId?{...day,candidates:{...(day.candidates??{}),[mainId]:(day.candidates?.[mainId]??[]).filter((item)=>item.id!==id)}}:day))}
  function promoteCandidate(mainId:string,id:string){setDays((items)=>items.map((day)=>{if(day.id!==activeDayId)return day;const index=day.places.findIndex((item)=>item.id===mainId);const alternatives=day.candidates?.[mainId]??[];const promoted=alternatives.find((item)=>item.id===id);if(index<0||!promoted)return day;const nextPlaces=[...day.places];const oldMain=nextPlaces[index];nextPlaces[index]=promoted;const candidates={...(day.candidates??{})};delete candidates[mainId];candidates[promoted.id]=[oldMain,...alternatives.filter((item)=>item.id!==id)];return {...day,places:nextPlaces,candidates}}));setLegs([])}
  function toggleSaved(place:Place){setSavedPlaces((items)=>items.some((item)=>item.id===place.id)?items.filter((item)=>item.id!==place.id):[place,...items])}
  function removePlace(id:string){setDays((items)=>items.map((day)=>{if(day.id!==activeDayId)return day;const candidates={...(day.candidates??{})};delete candidates[id];return {...day,places:day.places.filter((item)=>item.id!==id),candidates}}))}
  function movePlace(from:number,to:number){if(to<0||to>=places.length||from===to)return;setPlaces((items)=>{const next=[...items];const [moved]=next.splice(from,1);next.splice(to,0,moved);return next})}
  function beginDrag(index:number,event:ReactPointerEvent<HTMLButtonElement>){draggedIndex.current=index;setDragIndex(index);event.currentTarget.setPointerCapture(event.pointerId)}
  function continueDrag(event:ReactPointerEvent<HTMLButtonElement>){if(draggedIndex.current===null)return;const target=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>("[data-order-index]");if(!target)return;const to=Number(target.dataset.orderIndex);const from=draggedIndex.current;if(!Number.isInteger(to)||from===to)return;movePlace(from,to);draggedIndex.current=to;setDragIndex(to)}
  function endDrag(){draggedIndex.current=null;setDragIndex(null)}

  return <main className="app-shell">
    <header className="app-header"><div><p className="overline">자동차와 도보를 잇는 여행</p><h1>길담</h1></div><button className="profile" aria-label="프로필">CU</button></header>
    {tab==="plan"&&<section className="page plan-page"><div className="trip-hero"><div className="hero-top"><span>8월 24일–{23+days.length}일 · {days.length}일 여행</span><span className="weather">맑음 27°</span></div><h2>{activeTrip.title}<br/>날짜별로 이어가는 여행</h2><div className="hero-stats"><span>{activeDay.label}</span><span>경유지 {places.length}곳</span><span>자동 저장</span></div></div><div className="day-switcher" role="tablist" aria-label="여행 날짜">{days.map((day)=><div className={`day-tab ${day.id===activeDayId?"active":""}`} key={day.id}><button role="tab" aria-selected={day.id===activeDayId} className="day-select" onClick={()=>selectDay(day.id)}><strong>{day.label}</strong><span>{day.date}</span></button><button className="day-remove" onClick={()=>removeDay(day.id)} disabled={days.length<=1} aria-label={`${day.label} 삭제`}>×</button></div>)}<button className="add-day" onClick={addDay} disabled={days.length>=5} aria-label="여행 날짜 추가">＋</button></div><div className="plan-map"><NaverMap places={places} start={activeDay.start} goal={activeDay.goal} onRouteData={setLegs}/></div><SectionTitle title={`${activeDay.label} 일정`} subtitle="각 구간의 실시간 자동차 거리와 예상 시간이에요" action="전체 지도" onClick={()=>setTab("map")}/><div className={`timeline sortable ${dragIndex!==null?"is-sorting":""}`}><article className="timeline-item fixed-stop"><time>출발</time><div className="stop-dot">S</div><div className="stop-content"><h3>{activeDay.start.name}</h3><p>{activeDay.label} 출발지예요</p><LegSummary leg={legs[0]}/><div className="stop-actions"><button className="add-place" onClick={()=>chooseEndpoint("start")}>출발지 변경</button><button className="add-place" onClick={()=>chooseInsertion(0)} disabled={places.length>=5}>＋ 장소 추가</button></div></div></article>{places.map((place,index)=><ScheduleStop key={place.id} place={place} index={index} leg={legs[index+1]} alternatives={activeDay.candidates?.[place.id]??[]} dragging={dragIndex===index} onBeginDrag={beginDrag} onContinueDrag={continueDrag} onEndDrag={endDrag} onRemove={removePlace} onAddPlace={chooseInsertion} onAddCandidate={chooseCandidate} onRemoveCandidate={removeCandidate} onPromoteCandidate={promoteCandidate}/>)}<article className="timeline-item fixed-stop"><time>도착</time><div className="stop-dot">G</div><div className="stop-content"><h3>{activeDay.goal.name}</h3><p>{activeDay.goal.name==="목적지 미정"?"검색해서 목적지를 정해 주세요.":`${activeDay.label} 최종 목적지예요`}</p><div className="stop-actions"><button className="add-place" onClick={()=>chooseEndpoint("goal")}>목적지 변경</button></div></div></article></div><button className="primary-action" onClick={()=>setTab("map")}>변경된 경로 확인</button></section>}
    {tab==="map"&&<section className="page map-page"><div className="map-wrap"><NaverMap places={places} start={activeDay.start} goal={activeDay.goal}/><form className="place-search" onSubmit={search}><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="주소, 관광지, 식당을 검색하세요" aria-label="장소 검색"/><button disabled={searching}>{searching?"검색 중":"검색"}</button></form>{endpointTarget&&<div className="insertion-banner"><strong>{endpointTarget==="start"?"출발지":"목적지"}를 검색해 선택하세요</strong><button onClick={()=>{setEndpointTarget(null);setTab("plan")}}>취소</button></div>}{candidateFor!==null&&<div className="insertion-banner"><strong>{places.find((item)=>item.id===candidateFor)?.name} 후보 추가</strong><button onClick={()=>{setCandidateFor(null);setTab("plan")}}>취소</button></div>}{insertIndex!==null&&<div className="insertion-banner"><strong>{insertIndex===0?"S":insertIndex} ↔ {insertIndex===places.length?"G":insertIndex+1} 사이에 추가</strong><button onClick={()=>{setInsertIndex(null);setTab("plan")}}>취소</button></div>}{(results.length>0||searchError)&&<div className={`search-results ${insertIndex!==null||candidateFor!==null||endpointTarget!==null?"with-insertion":""}`}>{source==="geocoding"&&<p className="search-notice">현재는 주소 검색이 제공됩니다. API HUB 키를 추가하면 식당·카페도 검색할 수 있어요.</p>}{searchError&&<p className="search-error">{searchError}</p>}{results.map((place)=><article key={place.id}><div><strong>{place.name}</strong><p>{place.category} · {place.address}</p></div><div className="search-result-actions"><button className="save-place" onClick={()=>toggleSaved(place)}>{savedPlaces.some((item)=>item.id===place.id)?"♥ 저장됨":"♡ 저장"}</button><button onClick={()=>endpointTarget?setEndpoint(place):candidateFor?addCandidate(place):addPlace(place)} disabled={!endpointTarget&&!candidateFor&&places.some((item)=>item.id===place.id)}>{endpointTarget?`${endpointTarget==="start"?"출발지":"목적지"}로 설정`:candidateFor?"후보 등록":places.some((item)=>item.id===place.id)?"추가됨":insertIndex!==null?"여기에 추가":"경로 추가"}</button></div></article>)}</div>}</div><div className="rest-panel"><div className="panel-handle"/><SectionTitle compact title={`저장한 장소 ${savedPlaces.length}곳`} subtitle="내 장소에서 경로에 바로 추가해 보세요" action="전체 보기" onClick={()=>setTab("saved")}/>{savedPlaces.length?savedPlaces.map((place)=><article className="rest-card" key={place.id}><div className="rest-symbol">♡</div><div className="rest-copy"><h3>{place.name}</h3><p>{place.address}</p><span>{place.category}</span></div><button onClick={()=>endpointTarget?setEndpoint(place):candidateFor?addCandidate(place):addPlace(place)} disabled={!endpointTarget&&!candidateFor&&places.some((item)=>item.id===place.id)}>{endpointTarget?`${endpointTarget==="start"?"출발지":"목적지"}로 설정`:candidateFor?"후보 등록":places.some((item)=>item.id===place.id)?"추가됨":insertIndex!==null?"여기에 추가":"경로 추가"}</button></article>):<div className="saved-empty"><strong>저장한 장소가 없어요</strong><p>위 검색 결과에서 ♡ 저장을 눌러보세요.</p></div>}</div></section>}
    {tab==="trips"&&<section className="page trips-page"><SectionTitle title="내 여행" subtitle="날짜별 일정과 후보 장소를 여행 단위로 관리해요" action="＋ 새 여행" onClick={addTrip}/><div className="trip-list">{trips.map((trip)=><article className={`trip-card ${trip.id===activeTripId?"active":""}`} key={trip.id}><button className="trip-delete" onClick={()=>removeTrip(trip.id)} disabled={trips.length<=1} aria-label={`${trip.title} 삭제`}>×</button><span className="trip-status">{trip.id===activeTripId?"진행 중":"저장됨"}</span><h3>{trip.title}</h3><p>{trip.days[0]?.date} – {trip.days[trip.days.length-1]?.date}</p><div className="trip-meta"><span>{trip.days.length}일</span><span>장소 {trip.days.reduce((count,day)=>count+day.places.length,0)}곳</span></div><div className="trip-actions"><button onClick={()=>renameTrip(trip.id)}>이름 변경</button><button className="open-trip" onClick={()=>openTrip(trip.id)}>{trip.id===activeTripId?"일정 보기":"이 여행 열기"}</button></div></article>)}</div></section>}
    {tab==="saved"&&<section className="page saved-page"><SectionTitle title="내 장소" subtitle="여행에 다시 쓰고 싶은 장소를 모아두세요" action={`${savedPlaces.length}곳`}/><div className="saved-list">{savedPlaces.length?savedPlaces.map((place)=><article className="rest-card" key={place.id}><div className="rest-symbol">♥</div><div className="rest-copy"><h3>{place.name}</h3><p>{place.address}</p><span>{place.category}</span></div><button className="unsave-place" onClick={()=>toggleSaved(place)}>저장 해제</button></article>):<div className="saved-empty"><strong>아직 저장한 장소가 없어요</strong><p>지도에서 장소를 검색한 뒤 ♡ 저장을 눌러보세요.</p></div>}</div><button className="primary-action" onClick={()=>setTab("map")}>장소 검색하기</button></section>}
    <nav className="bottom-nav" aria-label="주요 메뉴"><button className={tab==="plan"?"active":""} onClick={()=>setTab("plan")}><span>⌂</span>일정</button><button className={tab==="trips"?"active":""} onClick={()=>setTab("trips")}><span>▣</span>여행</button><button className={tab==="saved"?"active":""} onClick={()=>setTab("saved")}><span>♡</span>내 장소</button></nav>
  </main>;
}
function SectionTitle({title,subtitle,action,onClick,compact=false}:{title:string;subtitle:string;action:string;onClick?:()=>void;compact?:boolean}){return <div className={`section-heading ${compact?"compact":""}`}><div><p>{title}</p><span>{subtitle}</span></div><button onClick={onClick}>{action}</button></div>}
function ScheduleStop({place,index,leg,alternatives,dragging,onBeginDrag,onContinueDrag,onEndDrag,onRemove,onAddPlace,onAddCandidate,onRemoveCandidate,onPromoteCandidate}:{place:Place;index:number;leg?:RouteLeg;alternatives:Place[];dragging:boolean;onBeginDrag:(index:number,event:ReactPointerEvent<HTMLButtonElement>)=>void;onContinueDrag:(event:ReactPointerEvent<HTMLButtonElement>)=>void;onEndDrag:()=>void;onRemove:(id:string)=>void;onAddPlace:(index:number)=>void;onAddCandidate:(id:string)=>void;onRemoveCandidate:(mainId:string,id:string)=>void;onPromoteCandidate:(mainId:string,id:string)=>void}){return <article data-order-index={index} className={`timeline-item user-stop candidate-stop ${dragging?"dragging":""}`}><button className="drag-handle" onPointerDown={(event)=>onBeginDrag(index,event)} onPointerMove={onContinueDrag} onPointerUp={onEndDrag} onPointerCancel={onEndDrag} aria-label={`${place.name} 순서 끌기`}>≡</button><div className="stop-dot">{index+1}</div><div className="candidate-carousel"><div className="candidate-track"><div className="candidate-slide"><span className="candidate-kind">메인 · 1/{alternatives.length+1}</span><h3>{place.name}</h3><p>{place.category} · {place.address}</p><LegSummary leg={leg}/><div className="stop-actions"><button className="remove-place" onClick={()=>onRemove(place.id)}>일정에서 삭제</button><button className="add-place" onClick={()=>onAddPlace(index+1)}>＋ 장소 추가</button><button className="candidate-add" onClick={()=>onAddCandidate(place.id)}>＋ 후보</button></div></div>{alternatives.map((candidate,i)=><div className="candidate-slide alternative" key={candidate.id}><span className="candidate-kind">후보 {i+1} · {i+2}/{alternatives.length+1}</span><h3>{candidate.name}</h3><p>{candidate.category} · {candidate.address}</p><span className="candidate-hint">좌우로 밀어 다른 후보 보기</span><div className="stop-actions"><button className="promote-candidate" onClick={()=>onPromoteCandidate(place.id,candidate.id)}>메인으로 변경</button><button className="remove-place" onClick={()=>onRemoveCandidate(place.id,candidate.id)}>후보 삭제</button></div></div>)}</div>{alternatives.length>0&&<span className="swipe-hint">‹ 좌우 스와이프 ›</span>}</div></article>}
function LegSummary({leg}:{leg?:RouteLeg}){if(!leg)return <span className="leg-summary loading">경로 계산 중…</span>;const km=leg.distance>=10000?`${Math.round(leg.distance/1000)}km`:`${(leg.distance/1000).toFixed(1)}km`;const minutes=Math.max(1,Math.round(leg.duration/60000));const time=minutes>=60?`${Math.floor(minutes/60)}시간 ${minutes%60?`${minutes%60}분`:""}`:`${minutes}분`;return <span className="leg-summary">자동차 · {km} · {time}</span>}
